[package]
name = "spin-archive"
version = "0.1.0"
authors = ["Andrew Vy <andrew@andrewvy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
rocket_contrib = { version = "0.4.4", default-features = false, features = ["tera_templates", "serve", "diesel_postgres_pool"] }
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.52"
diesel = { version = "1.4.4", features = ["postgres"] }
diesel_migrations = "1.4.0"
log = "0.4.8"

[build-dependencies]
vergen = "3.1.0"
